In [1]:
import numpy as np

In [2]:
state = {
    0: "Burger",
    1: "Pizza",
    2: "Hotdog"
}
state

{0: 'Burger', 1: 'Pizza', 2: 'Hotdog'}

Transiton matrix

In [4]:
A = np.array([[0.2, 0.6, 0.2],[0.3,0.0,0.7],[0.5,0.0,0.5]])
A

array([[0.2, 0.6, 0.2],
       [0.3, 0. , 0.7],
       [0.5, 0. , 0.5]])

Random Walk Now

In [5]:
n = 15
start_state = 0
print(state[start_state], "--->", end="")
prev_state = start_state

while n-1:
    curr_state = np.random.choice([0,1,2], p=A[prev_state])
    print(state[curr_state], "--->", end="")
    prev_state = curr_state
    n -= 1
print("END")

Burger --->Pizza --->Burger --->Pizza --->Hotdog --->Burger --->Pizza --->Hotdog --->Hotdog --->Hotdog --->Hotdog --->Burger --->Pizza --->Burger --->Pizza --->END


Now applying this to a monte carlo method

In [7]:
steps = 10**6
start_state = 0
pi = np.array([0,0,0])
pi[start_state] = 1
prev_state = start_state
i=0
while i<steps:
    curr_state = np.random.choice([0,1,2], p=A[prev_state])
    pi[curr_state] += 1
    prev_state = curr_state
    i +=1
print("pi = ", pi/steps)

pi =  [0.351445 0.210945 0.437611]


Repeated Matrix Multiplication

In [10]:
steps = 10**3
A_n =A
i = 0
while i<steps:
    A_n = np.matmul(A_n,A)
    i += 1
print("A_n = ", A_n)
print("pi = ", A_n[0])

A_n =  [[0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]]
pi =  [0.35211268 0.21126761 0.43661972]


Finding left eigen vectors

In [14]:
import scipy.linalg
values, left = scipy.linalg.eig(A, left=True, right=False)

print("Eigenvector = \n", left)
print("Eigenvalues = ", values)



Eigenvector = 
 [[-0.58746336+0.j         -0.16984156-0.35355339j -0.16984156+0.35355339j]
 [-0.35247801+0.j          0.67936622+0.j          0.67936622-0.j        ]
 [-0.72845456+0.j         -0.50952467+0.35355339j -0.50952467-0.35355339j]]
Eigenvalues =  [ 1.  +0.j        -0.15+0.3122499j -0.15-0.3122499j]


In [15]:
#Normalizing the eigenvector
pi = left[:,0]
pi_normalized = [(x/np.sum(pi)).real for x in pi]
pi_normalized

[0.3521126760563379, 0.21126760563380292, 0.43661971830985913]